linters:
  enable:
    - golint
    - staticcheck
    - errcheck
    - gosimple
    - unused
  disable:
    - gocyclo
  issues:
    exclude-rules:
      - text: "error return value not checked"
        linters:
          - errcheck
  run:
    concurrency: 4
    timeout: 3m
