// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/alexeyvas94/main_project/internal/service.CarService -o car_service_minimock.go -n CarServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/alexeyvas94/main_project/internal/models"
	pb "github.com/alexeyvas94/main_project/pkg/car"
	"github.com/gojuno/minimock/v3"
)

// CarServiceMock implements mm_service.CarService
type CarServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateCar          func(ctx context.Context, req *pb.CreateRequest) (i1 int64, err error)
	funcCreateCarOrigin    string
	inspectFuncCreateCar   func(ctx context.Context, req *pb.CreateRequest)
	afterCreateCarCounter  uint64
	beforeCreateCarCounter uint64
	CreateCarMock          mCarServiceMockCreateCar

	funcDeleteCar          func(ctx context.Context, id int64) (err error)
	funcDeleteCarOrigin    string
	inspectFuncDeleteCar   func(ctx context.Context, id int64)
	afterDeleteCarCounter  uint64
	beforeDeleteCarCounter uint64
	DeleteCarMock          mCarServiceMockDeleteCar

	funcGetCar          func(ctx context.Context, id int64) (cp1 *models.Car, err error)
	funcGetCarOrigin    string
	inspectFuncGetCar   func(ctx context.Context, id int64)
	afterGetCarCounter  uint64
	beforeGetCarCounter uint64
	GetCarMock          mCarServiceMockGetCar

	funcUpdateCar          func(ctx context.Context, req *pb.UpdateRequest) (err error)
	funcUpdateCarOrigin    string
	inspectFuncUpdateCar   func(ctx context.Context, req *pb.UpdateRequest)
	afterUpdateCarCounter  uint64
	beforeUpdateCarCounter uint64
	UpdateCarMock          mCarServiceMockUpdateCar
}

// NewCarServiceMock returns a mock for mm_service.CarService
func NewCarServiceMock(t minimock.Tester) *CarServiceMock {
	m := &CarServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateCarMock = mCarServiceMockCreateCar{mock: m}
	m.CreateCarMock.callArgs = []*CarServiceMockCreateCarParams{}

	m.DeleteCarMock = mCarServiceMockDeleteCar{mock: m}
	m.DeleteCarMock.callArgs = []*CarServiceMockDeleteCarParams{}

	m.GetCarMock = mCarServiceMockGetCar{mock: m}
	m.GetCarMock.callArgs = []*CarServiceMockGetCarParams{}

	m.UpdateCarMock = mCarServiceMockUpdateCar{mock: m}
	m.UpdateCarMock.callArgs = []*CarServiceMockUpdateCarParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCarServiceMockCreateCar struct {
	optional           bool
	mock               *CarServiceMock
	defaultExpectation *CarServiceMockCreateCarExpectation
	expectations       []*CarServiceMockCreateCarExpectation

	callArgs []*CarServiceMockCreateCarParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CarServiceMockCreateCarExpectation specifies expectation struct of the CarService.CreateCar
type CarServiceMockCreateCarExpectation struct {
	mock               *CarServiceMock
	params             *CarServiceMockCreateCarParams
	paramPtrs          *CarServiceMockCreateCarParamPtrs
	expectationOrigins CarServiceMockCreateCarExpectationOrigins
	results            *CarServiceMockCreateCarResults
	returnOrigin       string
	Counter            uint64
}

// CarServiceMockCreateCarParams contains parameters of the CarService.CreateCar
type CarServiceMockCreateCarParams struct {
	ctx context.Context
	req *pb.CreateRequest
}

// CarServiceMockCreateCarParamPtrs contains pointers to parameters of the CarService.CreateCar
type CarServiceMockCreateCarParamPtrs struct {
	ctx *context.Context
	req **pb.CreateRequest
}

// CarServiceMockCreateCarResults contains results of the CarService.CreateCar
type CarServiceMockCreateCarResults struct {
	i1  int64
	err error
}

// CarServiceMockCreateCarOrigins contains origins of expectations of the CarService.CreateCar
type CarServiceMockCreateCarExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateCar *mCarServiceMockCreateCar) Optional() *mCarServiceMockCreateCar {
	mmCreateCar.optional = true
	return mmCreateCar
}

// Expect sets up expected params for CarService.CreateCar
func (mmCreateCar *mCarServiceMockCreateCar) Expect(ctx context.Context, req *pb.CreateRequest) *mCarServiceMockCreateCar {
	if mmCreateCar.mock.funcCreateCar != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Set")
	}

	if mmCreateCar.defaultExpectation == nil {
		mmCreateCar.defaultExpectation = &CarServiceMockCreateCarExpectation{}
	}

	if mmCreateCar.defaultExpectation.paramPtrs != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by ExpectParams functions")
	}

	mmCreateCar.defaultExpectation.params = &CarServiceMockCreateCarParams{ctx, req}
	mmCreateCar.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateCar.expectations {
		if minimock.Equal(e.params, mmCreateCar.defaultExpectation.params) {
			mmCreateCar.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateCar.defaultExpectation.params)
		}
	}

	return mmCreateCar
}

// ExpectCtxParam1 sets up expected param ctx for CarService.CreateCar
func (mmCreateCar *mCarServiceMockCreateCar) ExpectCtxParam1(ctx context.Context) *mCarServiceMockCreateCar {
	if mmCreateCar.mock.funcCreateCar != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Set")
	}

	if mmCreateCar.defaultExpectation == nil {
		mmCreateCar.defaultExpectation = &CarServiceMockCreateCarExpectation{}
	}

	if mmCreateCar.defaultExpectation.params != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Expect")
	}

	if mmCreateCar.defaultExpectation.paramPtrs == nil {
		mmCreateCar.defaultExpectation.paramPtrs = &CarServiceMockCreateCarParamPtrs{}
	}
	mmCreateCar.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateCar.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateCar
}

// ExpectReqParam2 sets up expected param req for CarService.CreateCar
func (mmCreateCar *mCarServiceMockCreateCar) ExpectReqParam2(req *pb.CreateRequest) *mCarServiceMockCreateCar {
	if mmCreateCar.mock.funcCreateCar != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Set")
	}

	if mmCreateCar.defaultExpectation == nil {
		mmCreateCar.defaultExpectation = &CarServiceMockCreateCarExpectation{}
	}

	if mmCreateCar.defaultExpectation.params != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Expect")
	}

	if mmCreateCar.defaultExpectation.paramPtrs == nil {
		mmCreateCar.defaultExpectation.paramPtrs = &CarServiceMockCreateCarParamPtrs{}
	}
	mmCreateCar.defaultExpectation.paramPtrs.req = &req
	mmCreateCar.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmCreateCar
}

// Inspect accepts an inspector function that has same arguments as the CarService.CreateCar
func (mmCreateCar *mCarServiceMockCreateCar) Inspect(f func(ctx context.Context, req *pb.CreateRequest)) *mCarServiceMockCreateCar {
	if mmCreateCar.mock.inspectFuncCreateCar != nil {
		mmCreateCar.mock.t.Fatalf("Inspect function is already set for CarServiceMock.CreateCar")
	}

	mmCreateCar.mock.inspectFuncCreateCar = f

	return mmCreateCar
}

// Return sets up results that will be returned by CarService.CreateCar
func (mmCreateCar *mCarServiceMockCreateCar) Return(i1 int64, err error) *CarServiceMock {
	if mmCreateCar.mock.funcCreateCar != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Set")
	}

	if mmCreateCar.defaultExpectation == nil {
		mmCreateCar.defaultExpectation = &CarServiceMockCreateCarExpectation{mock: mmCreateCar.mock}
	}
	mmCreateCar.defaultExpectation.results = &CarServiceMockCreateCarResults{i1, err}
	mmCreateCar.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateCar.mock
}

// Set uses given function f to mock the CarService.CreateCar method
func (mmCreateCar *mCarServiceMockCreateCar) Set(f func(ctx context.Context, req *pb.CreateRequest) (i1 int64, err error)) *CarServiceMock {
	if mmCreateCar.defaultExpectation != nil {
		mmCreateCar.mock.t.Fatalf("Default expectation is already set for the CarService.CreateCar method")
	}

	if len(mmCreateCar.expectations) > 0 {
		mmCreateCar.mock.t.Fatalf("Some expectations are already set for the CarService.CreateCar method")
	}

	mmCreateCar.mock.funcCreateCar = f
	mmCreateCar.mock.funcCreateCarOrigin = minimock.CallerInfo(1)
	return mmCreateCar.mock
}

// When sets expectation for the CarService.CreateCar which will trigger the result defined by the following
// Then helper
func (mmCreateCar *mCarServiceMockCreateCar) When(ctx context.Context, req *pb.CreateRequest) *CarServiceMockCreateCarExpectation {
	if mmCreateCar.mock.funcCreateCar != nil {
		mmCreateCar.mock.t.Fatalf("CarServiceMock.CreateCar mock is already set by Set")
	}

	expectation := &CarServiceMockCreateCarExpectation{
		mock:               mmCreateCar.mock,
		params:             &CarServiceMockCreateCarParams{ctx, req},
		expectationOrigins: CarServiceMockCreateCarExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateCar.expectations = append(mmCreateCar.expectations, expectation)
	return expectation
}

// Then sets up CarService.CreateCar return parameters for the expectation previously defined by the When method
func (e *CarServiceMockCreateCarExpectation) Then(i1 int64, err error) *CarServiceMock {
	e.results = &CarServiceMockCreateCarResults{i1, err}
	return e.mock
}

// Times sets number of times CarService.CreateCar should be invoked
func (mmCreateCar *mCarServiceMockCreateCar) Times(n uint64) *mCarServiceMockCreateCar {
	if n == 0 {
		mmCreateCar.mock.t.Fatalf("Times of CarServiceMock.CreateCar mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateCar.expectedInvocations, n)
	mmCreateCar.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateCar
}

func (mmCreateCar *mCarServiceMockCreateCar) invocationsDone() bool {
	if len(mmCreateCar.expectations) == 0 && mmCreateCar.defaultExpectation == nil && mmCreateCar.mock.funcCreateCar == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateCar.mock.afterCreateCarCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateCar.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateCar implements mm_service.CarService
func (mmCreateCar *CarServiceMock) CreateCar(ctx context.Context, req *pb.CreateRequest) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateCar.beforeCreateCarCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateCar.afterCreateCarCounter, 1)

	mmCreateCar.t.Helper()

	if mmCreateCar.inspectFuncCreateCar != nil {
		mmCreateCar.inspectFuncCreateCar(ctx, req)
	}

	mm_params := CarServiceMockCreateCarParams{ctx, req}

	// Record call args
	mmCreateCar.CreateCarMock.mutex.Lock()
	mmCreateCar.CreateCarMock.callArgs = append(mmCreateCar.CreateCarMock.callArgs, &mm_params)
	mmCreateCar.CreateCarMock.mutex.Unlock()

	for _, e := range mmCreateCar.CreateCarMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateCar.CreateCarMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateCar.CreateCarMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateCar.CreateCarMock.defaultExpectation.params
		mm_want_ptrs := mmCreateCar.CreateCarMock.defaultExpectation.paramPtrs

		mm_got := CarServiceMockCreateCarParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateCar.t.Errorf("CarServiceMock.CreateCar got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateCar.CreateCarMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmCreateCar.t.Errorf("CarServiceMock.CreateCar got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateCar.CreateCarMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateCar.t.Errorf("CarServiceMock.CreateCar got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateCar.CreateCarMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateCar.CreateCarMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateCar.t.Fatal("No results are set for the CarServiceMock.CreateCar")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateCar.funcCreateCar != nil {
		return mmCreateCar.funcCreateCar(ctx, req)
	}
	mmCreateCar.t.Fatalf("Unexpected call to CarServiceMock.CreateCar. %v %v", ctx, req)
	return
}

// CreateCarAfterCounter returns a count of finished CarServiceMock.CreateCar invocations
func (mmCreateCar *CarServiceMock) CreateCarAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCar.afterCreateCarCounter)
}

// CreateCarBeforeCounter returns a count of CarServiceMock.CreateCar invocations
func (mmCreateCar *CarServiceMock) CreateCarBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCar.beforeCreateCarCounter)
}

// Calls returns a list of arguments used in each call to CarServiceMock.CreateCar.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateCar *mCarServiceMockCreateCar) Calls() []*CarServiceMockCreateCarParams {
	mmCreateCar.mutex.RLock()

	argCopy := make([]*CarServiceMockCreateCarParams, len(mmCreateCar.callArgs))
	copy(argCopy, mmCreateCar.callArgs)

	mmCreateCar.mutex.RUnlock()

	return argCopy
}

// MinimockCreateCarDone returns true if the count of the CreateCar invocations corresponds
// the number of defined expectations
func (m *CarServiceMock) MinimockCreateCarDone() bool {
	if m.CreateCarMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateCarMock.invocationsDone()
}

// MinimockCreateCarInspect logs each unmet expectation
func (m *CarServiceMock) MinimockCreateCarInspect() {
	for _, e := range m.CreateCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CarServiceMock.CreateCar at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCarCounter := mm_atomic.LoadUint64(&m.afterCreateCarCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCarMock.defaultExpectation != nil && afterCreateCarCounter < 1 {
		if m.CreateCarMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CarServiceMock.CreateCar at\n%s", m.CreateCarMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CarServiceMock.CreateCar at\n%s with params: %#v", m.CreateCarMock.defaultExpectation.expectationOrigins.origin, *m.CreateCarMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateCar != nil && afterCreateCarCounter < 1 {
		m.t.Errorf("Expected call to CarServiceMock.CreateCar at\n%s", m.funcCreateCarOrigin)
	}

	if !m.CreateCarMock.invocationsDone() && afterCreateCarCounter > 0 {
		m.t.Errorf("Expected %d calls to CarServiceMock.CreateCar at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateCarMock.expectedInvocations), m.CreateCarMock.expectedInvocationsOrigin, afterCreateCarCounter)
	}
}

type mCarServiceMockDeleteCar struct {
	optional           bool
	mock               *CarServiceMock
	defaultExpectation *CarServiceMockDeleteCarExpectation
	expectations       []*CarServiceMockDeleteCarExpectation

	callArgs []*CarServiceMockDeleteCarParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CarServiceMockDeleteCarExpectation specifies expectation struct of the CarService.DeleteCar
type CarServiceMockDeleteCarExpectation struct {
	mock               *CarServiceMock
	params             *CarServiceMockDeleteCarParams
	paramPtrs          *CarServiceMockDeleteCarParamPtrs
	expectationOrigins CarServiceMockDeleteCarExpectationOrigins
	results            *CarServiceMockDeleteCarResults
	returnOrigin       string
	Counter            uint64
}

// CarServiceMockDeleteCarParams contains parameters of the CarService.DeleteCar
type CarServiceMockDeleteCarParams struct {
	ctx context.Context
	id  int64
}

// CarServiceMockDeleteCarParamPtrs contains pointers to parameters of the CarService.DeleteCar
type CarServiceMockDeleteCarParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// CarServiceMockDeleteCarResults contains results of the CarService.DeleteCar
type CarServiceMockDeleteCarResults struct {
	err error
}

// CarServiceMockDeleteCarOrigins contains origins of expectations of the CarService.DeleteCar
type CarServiceMockDeleteCarExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteCar *mCarServiceMockDeleteCar) Optional() *mCarServiceMockDeleteCar {
	mmDeleteCar.optional = true
	return mmDeleteCar
}

// Expect sets up expected params for CarService.DeleteCar
func (mmDeleteCar *mCarServiceMockDeleteCar) Expect(ctx context.Context, id int64) *mCarServiceMockDeleteCar {
	if mmDeleteCar.mock.funcDeleteCar != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Set")
	}

	if mmDeleteCar.defaultExpectation == nil {
		mmDeleteCar.defaultExpectation = &CarServiceMockDeleteCarExpectation{}
	}

	if mmDeleteCar.defaultExpectation.paramPtrs != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by ExpectParams functions")
	}

	mmDeleteCar.defaultExpectation.params = &CarServiceMockDeleteCarParams{ctx, id}
	mmDeleteCar.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteCar.expectations {
		if minimock.Equal(e.params, mmDeleteCar.defaultExpectation.params) {
			mmDeleteCar.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteCar.defaultExpectation.params)
		}
	}

	return mmDeleteCar
}

// ExpectCtxParam1 sets up expected param ctx for CarService.DeleteCar
func (mmDeleteCar *mCarServiceMockDeleteCar) ExpectCtxParam1(ctx context.Context) *mCarServiceMockDeleteCar {
	if mmDeleteCar.mock.funcDeleteCar != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Set")
	}

	if mmDeleteCar.defaultExpectation == nil {
		mmDeleteCar.defaultExpectation = &CarServiceMockDeleteCarExpectation{}
	}

	if mmDeleteCar.defaultExpectation.params != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Expect")
	}

	if mmDeleteCar.defaultExpectation.paramPtrs == nil {
		mmDeleteCar.defaultExpectation.paramPtrs = &CarServiceMockDeleteCarParamPtrs{}
	}
	mmDeleteCar.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteCar.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteCar
}

// ExpectIdParam2 sets up expected param id for CarService.DeleteCar
func (mmDeleteCar *mCarServiceMockDeleteCar) ExpectIdParam2(id int64) *mCarServiceMockDeleteCar {
	if mmDeleteCar.mock.funcDeleteCar != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Set")
	}

	if mmDeleteCar.defaultExpectation == nil {
		mmDeleteCar.defaultExpectation = &CarServiceMockDeleteCarExpectation{}
	}

	if mmDeleteCar.defaultExpectation.params != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Expect")
	}

	if mmDeleteCar.defaultExpectation.paramPtrs == nil {
		mmDeleteCar.defaultExpectation.paramPtrs = &CarServiceMockDeleteCarParamPtrs{}
	}
	mmDeleteCar.defaultExpectation.paramPtrs.id = &id
	mmDeleteCar.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDeleteCar
}

// Inspect accepts an inspector function that has same arguments as the CarService.DeleteCar
func (mmDeleteCar *mCarServiceMockDeleteCar) Inspect(f func(ctx context.Context, id int64)) *mCarServiceMockDeleteCar {
	if mmDeleteCar.mock.inspectFuncDeleteCar != nil {
		mmDeleteCar.mock.t.Fatalf("Inspect function is already set for CarServiceMock.DeleteCar")
	}

	mmDeleteCar.mock.inspectFuncDeleteCar = f

	return mmDeleteCar
}

// Return sets up results that will be returned by CarService.DeleteCar
func (mmDeleteCar *mCarServiceMockDeleteCar) Return(err error) *CarServiceMock {
	if mmDeleteCar.mock.funcDeleteCar != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Set")
	}

	if mmDeleteCar.defaultExpectation == nil {
		mmDeleteCar.defaultExpectation = &CarServiceMockDeleteCarExpectation{mock: mmDeleteCar.mock}
	}
	mmDeleteCar.defaultExpectation.results = &CarServiceMockDeleteCarResults{err}
	mmDeleteCar.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteCar.mock
}

// Set uses given function f to mock the CarService.DeleteCar method
func (mmDeleteCar *mCarServiceMockDeleteCar) Set(f func(ctx context.Context, id int64) (err error)) *CarServiceMock {
	if mmDeleteCar.defaultExpectation != nil {
		mmDeleteCar.mock.t.Fatalf("Default expectation is already set for the CarService.DeleteCar method")
	}

	if len(mmDeleteCar.expectations) > 0 {
		mmDeleteCar.mock.t.Fatalf("Some expectations are already set for the CarService.DeleteCar method")
	}

	mmDeleteCar.mock.funcDeleteCar = f
	mmDeleteCar.mock.funcDeleteCarOrigin = minimock.CallerInfo(1)
	return mmDeleteCar.mock
}

// When sets expectation for the CarService.DeleteCar which will trigger the result defined by the following
// Then helper
func (mmDeleteCar *mCarServiceMockDeleteCar) When(ctx context.Context, id int64) *CarServiceMockDeleteCarExpectation {
	if mmDeleteCar.mock.funcDeleteCar != nil {
		mmDeleteCar.mock.t.Fatalf("CarServiceMock.DeleteCar mock is already set by Set")
	}

	expectation := &CarServiceMockDeleteCarExpectation{
		mock:               mmDeleteCar.mock,
		params:             &CarServiceMockDeleteCarParams{ctx, id},
		expectationOrigins: CarServiceMockDeleteCarExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteCar.expectations = append(mmDeleteCar.expectations, expectation)
	return expectation
}

// Then sets up CarService.DeleteCar return parameters for the expectation previously defined by the When method
func (e *CarServiceMockDeleteCarExpectation) Then(err error) *CarServiceMock {
	e.results = &CarServiceMockDeleteCarResults{err}
	return e.mock
}

// Times sets number of times CarService.DeleteCar should be invoked
func (mmDeleteCar *mCarServiceMockDeleteCar) Times(n uint64) *mCarServiceMockDeleteCar {
	if n == 0 {
		mmDeleteCar.mock.t.Fatalf("Times of CarServiceMock.DeleteCar mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteCar.expectedInvocations, n)
	mmDeleteCar.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteCar
}

func (mmDeleteCar *mCarServiceMockDeleteCar) invocationsDone() bool {
	if len(mmDeleteCar.expectations) == 0 && mmDeleteCar.defaultExpectation == nil && mmDeleteCar.mock.funcDeleteCar == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteCar.mock.afterDeleteCarCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteCar.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteCar implements mm_service.CarService
func (mmDeleteCar *CarServiceMock) DeleteCar(ctx context.Context, id int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteCar.beforeDeleteCarCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteCar.afterDeleteCarCounter, 1)

	mmDeleteCar.t.Helper()

	if mmDeleteCar.inspectFuncDeleteCar != nil {
		mmDeleteCar.inspectFuncDeleteCar(ctx, id)
	}

	mm_params := CarServiceMockDeleteCarParams{ctx, id}

	// Record call args
	mmDeleteCar.DeleteCarMock.mutex.Lock()
	mmDeleteCar.DeleteCarMock.callArgs = append(mmDeleteCar.DeleteCarMock.callArgs, &mm_params)
	mmDeleteCar.DeleteCarMock.mutex.Unlock()

	for _, e := range mmDeleteCar.DeleteCarMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteCar.DeleteCarMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteCar.DeleteCarMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteCar.DeleteCarMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteCar.DeleteCarMock.defaultExpectation.paramPtrs

		mm_got := CarServiceMockDeleteCarParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteCar.t.Errorf("CarServiceMock.DeleteCar got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteCar.DeleteCarMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDeleteCar.t.Errorf("CarServiceMock.DeleteCar got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteCar.DeleteCarMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteCar.t.Errorf("CarServiceMock.DeleteCar got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteCar.DeleteCarMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteCar.DeleteCarMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteCar.t.Fatal("No results are set for the CarServiceMock.DeleteCar")
		}
		return (*mm_results).err
	}
	if mmDeleteCar.funcDeleteCar != nil {
		return mmDeleteCar.funcDeleteCar(ctx, id)
	}
	mmDeleteCar.t.Fatalf("Unexpected call to CarServiceMock.DeleteCar. %v %v", ctx, id)
	return
}

// DeleteCarAfterCounter returns a count of finished CarServiceMock.DeleteCar invocations
func (mmDeleteCar *CarServiceMock) DeleteCarAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteCar.afterDeleteCarCounter)
}

// DeleteCarBeforeCounter returns a count of CarServiceMock.DeleteCar invocations
func (mmDeleteCar *CarServiceMock) DeleteCarBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteCar.beforeDeleteCarCounter)
}

// Calls returns a list of arguments used in each call to CarServiceMock.DeleteCar.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteCar *mCarServiceMockDeleteCar) Calls() []*CarServiceMockDeleteCarParams {
	mmDeleteCar.mutex.RLock()

	argCopy := make([]*CarServiceMockDeleteCarParams, len(mmDeleteCar.callArgs))
	copy(argCopy, mmDeleteCar.callArgs)

	mmDeleteCar.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteCarDone returns true if the count of the DeleteCar invocations corresponds
// the number of defined expectations
func (m *CarServiceMock) MinimockDeleteCarDone() bool {
	if m.DeleteCarMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteCarMock.invocationsDone()
}

// MinimockDeleteCarInspect logs each unmet expectation
func (m *CarServiceMock) MinimockDeleteCarInspect() {
	for _, e := range m.DeleteCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CarServiceMock.DeleteCar at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCarCounter := mm_atomic.LoadUint64(&m.afterDeleteCarCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteCarMock.defaultExpectation != nil && afterDeleteCarCounter < 1 {
		if m.DeleteCarMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CarServiceMock.DeleteCar at\n%s", m.DeleteCarMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CarServiceMock.DeleteCar at\n%s with params: %#v", m.DeleteCarMock.defaultExpectation.expectationOrigins.origin, *m.DeleteCarMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteCar != nil && afterDeleteCarCounter < 1 {
		m.t.Errorf("Expected call to CarServiceMock.DeleteCar at\n%s", m.funcDeleteCarOrigin)
	}

	if !m.DeleteCarMock.invocationsDone() && afterDeleteCarCounter > 0 {
		m.t.Errorf("Expected %d calls to CarServiceMock.DeleteCar at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteCarMock.expectedInvocations), m.DeleteCarMock.expectedInvocationsOrigin, afterDeleteCarCounter)
	}
}

type mCarServiceMockGetCar struct {
	optional           bool
	mock               *CarServiceMock
	defaultExpectation *CarServiceMockGetCarExpectation
	expectations       []*CarServiceMockGetCarExpectation

	callArgs []*CarServiceMockGetCarParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CarServiceMockGetCarExpectation specifies expectation struct of the CarService.GetCar
type CarServiceMockGetCarExpectation struct {
	mock               *CarServiceMock
	params             *CarServiceMockGetCarParams
	paramPtrs          *CarServiceMockGetCarParamPtrs
	expectationOrigins CarServiceMockGetCarExpectationOrigins
	results            *CarServiceMockGetCarResults
	returnOrigin       string
	Counter            uint64
}

// CarServiceMockGetCarParams contains parameters of the CarService.GetCar
type CarServiceMockGetCarParams struct {
	ctx context.Context
	id  int64
}

// CarServiceMockGetCarParamPtrs contains pointers to parameters of the CarService.GetCar
type CarServiceMockGetCarParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// CarServiceMockGetCarResults contains results of the CarService.GetCar
type CarServiceMockGetCarResults struct {
	cp1 *models.Car
	err error
}

// CarServiceMockGetCarOrigins contains origins of expectations of the CarService.GetCar
type CarServiceMockGetCarExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetCar *mCarServiceMockGetCar) Optional() *mCarServiceMockGetCar {
	mmGetCar.optional = true
	return mmGetCar
}

// Expect sets up expected params for CarService.GetCar
func (mmGetCar *mCarServiceMockGetCar) Expect(ctx context.Context, id int64) *mCarServiceMockGetCar {
	if mmGetCar.mock.funcGetCar != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Set")
	}

	if mmGetCar.defaultExpectation == nil {
		mmGetCar.defaultExpectation = &CarServiceMockGetCarExpectation{}
	}

	if mmGetCar.defaultExpectation.paramPtrs != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by ExpectParams functions")
	}

	mmGetCar.defaultExpectation.params = &CarServiceMockGetCarParams{ctx, id}
	mmGetCar.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetCar.expectations {
		if minimock.Equal(e.params, mmGetCar.defaultExpectation.params) {
			mmGetCar.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetCar.defaultExpectation.params)
		}
	}

	return mmGetCar
}

// ExpectCtxParam1 sets up expected param ctx for CarService.GetCar
func (mmGetCar *mCarServiceMockGetCar) ExpectCtxParam1(ctx context.Context) *mCarServiceMockGetCar {
	if mmGetCar.mock.funcGetCar != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Set")
	}

	if mmGetCar.defaultExpectation == nil {
		mmGetCar.defaultExpectation = &CarServiceMockGetCarExpectation{}
	}

	if mmGetCar.defaultExpectation.params != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Expect")
	}

	if mmGetCar.defaultExpectation.paramPtrs == nil {
		mmGetCar.defaultExpectation.paramPtrs = &CarServiceMockGetCarParamPtrs{}
	}
	mmGetCar.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetCar.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetCar
}

// ExpectIdParam2 sets up expected param id for CarService.GetCar
func (mmGetCar *mCarServiceMockGetCar) ExpectIdParam2(id int64) *mCarServiceMockGetCar {
	if mmGetCar.mock.funcGetCar != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Set")
	}

	if mmGetCar.defaultExpectation == nil {
		mmGetCar.defaultExpectation = &CarServiceMockGetCarExpectation{}
	}

	if mmGetCar.defaultExpectation.params != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Expect")
	}

	if mmGetCar.defaultExpectation.paramPtrs == nil {
		mmGetCar.defaultExpectation.paramPtrs = &CarServiceMockGetCarParamPtrs{}
	}
	mmGetCar.defaultExpectation.paramPtrs.id = &id
	mmGetCar.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetCar
}

// Inspect accepts an inspector function that has same arguments as the CarService.GetCar
func (mmGetCar *mCarServiceMockGetCar) Inspect(f func(ctx context.Context, id int64)) *mCarServiceMockGetCar {
	if mmGetCar.mock.inspectFuncGetCar != nil {
		mmGetCar.mock.t.Fatalf("Inspect function is already set for CarServiceMock.GetCar")
	}

	mmGetCar.mock.inspectFuncGetCar = f

	return mmGetCar
}

// Return sets up results that will be returned by CarService.GetCar
func (mmGetCar *mCarServiceMockGetCar) Return(cp1 *models.Car, err error) *CarServiceMock {
	if mmGetCar.mock.funcGetCar != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Set")
	}

	if mmGetCar.defaultExpectation == nil {
		mmGetCar.defaultExpectation = &CarServiceMockGetCarExpectation{mock: mmGetCar.mock}
	}
	mmGetCar.defaultExpectation.results = &CarServiceMockGetCarResults{cp1, err}
	mmGetCar.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetCar.mock
}

// Set uses given function f to mock the CarService.GetCar method
func (mmGetCar *mCarServiceMockGetCar) Set(f func(ctx context.Context, id int64) (cp1 *models.Car, err error)) *CarServiceMock {
	if mmGetCar.defaultExpectation != nil {
		mmGetCar.mock.t.Fatalf("Default expectation is already set for the CarService.GetCar method")
	}

	if len(mmGetCar.expectations) > 0 {
		mmGetCar.mock.t.Fatalf("Some expectations are already set for the CarService.GetCar method")
	}

	mmGetCar.mock.funcGetCar = f
	mmGetCar.mock.funcGetCarOrigin = minimock.CallerInfo(1)
	return mmGetCar.mock
}

// When sets expectation for the CarService.GetCar which will trigger the result defined by the following
// Then helper
func (mmGetCar *mCarServiceMockGetCar) When(ctx context.Context, id int64) *CarServiceMockGetCarExpectation {
	if mmGetCar.mock.funcGetCar != nil {
		mmGetCar.mock.t.Fatalf("CarServiceMock.GetCar mock is already set by Set")
	}

	expectation := &CarServiceMockGetCarExpectation{
		mock:               mmGetCar.mock,
		params:             &CarServiceMockGetCarParams{ctx, id},
		expectationOrigins: CarServiceMockGetCarExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetCar.expectations = append(mmGetCar.expectations, expectation)
	return expectation
}

// Then sets up CarService.GetCar return parameters for the expectation previously defined by the When method
func (e *CarServiceMockGetCarExpectation) Then(cp1 *models.Car, err error) *CarServiceMock {
	e.results = &CarServiceMockGetCarResults{cp1, err}
	return e.mock
}

// Times sets number of times CarService.GetCar should be invoked
func (mmGetCar *mCarServiceMockGetCar) Times(n uint64) *mCarServiceMockGetCar {
	if n == 0 {
		mmGetCar.mock.t.Fatalf("Times of CarServiceMock.GetCar mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetCar.expectedInvocations, n)
	mmGetCar.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetCar
}

func (mmGetCar *mCarServiceMockGetCar) invocationsDone() bool {
	if len(mmGetCar.expectations) == 0 && mmGetCar.defaultExpectation == nil && mmGetCar.mock.funcGetCar == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetCar.mock.afterGetCarCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetCar.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetCar implements mm_service.CarService
func (mmGetCar *CarServiceMock) GetCar(ctx context.Context, id int64) (cp1 *models.Car, err error) {
	mm_atomic.AddUint64(&mmGetCar.beforeGetCarCounter, 1)
	defer mm_atomic.AddUint64(&mmGetCar.afterGetCarCounter, 1)

	mmGetCar.t.Helper()

	if mmGetCar.inspectFuncGetCar != nil {
		mmGetCar.inspectFuncGetCar(ctx, id)
	}

	mm_params := CarServiceMockGetCarParams{ctx, id}

	// Record call args
	mmGetCar.GetCarMock.mutex.Lock()
	mmGetCar.GetCarMock.callArgs = append(mmGetCar.GetCarMock.callArgs, &mm_params)
	mmGetCar.GetCarMock.mutex.Unlock()

	for _, e := range mmGetCar.GetCarMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetCar.GetCarMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetCar.GetCarMock.defaultExpectation.Counter, 1)
		mm_want := mmGetCar.GetCarMock.defaultExpectation.params
		mm_want_ptrs := mmGetCar.GetCarMock.defaultExpectation.paramPtrs

		mm_got := CarServiceMockGetCarParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetCar.t.Errorf("CarServiceMock.GetCar got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetCar.GetCarMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetCar.t.Errorf("CarServiceMock.GetCar got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetCar.GetCarMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetCar.t.Errorf("CarServiceMock.GetCar got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetCar.GetCarMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetCar.GetCarMock.defaultExpectation.results
		if mm_results == nil {
			mmGetCar.t.Fatal("No results are set for the CarServiceMock.GetCar")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetCar.funcGetCar != nil {
		return mmGetCar.funcGetCar(ctx, id)
	}
	mmGetCar.t.Fatalf("Unexpected call to CarServiceMock.GetCar. %v %v", ctx, id)
	return
}

// GetCarAfterCounter returns a count of finished CarServiceMock.GetCar invocations
func (mmGetCar *CarServiceMock) GetCarAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCar.afterGetCarCounter)
}

// GetCarBeforeCounter returns a count of CarServiceMock.GetCar invocations
func (mmGetCar *CarServiceMock) GetCarBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCar.beforeGetCarCounter)
}

// Calls returns a list of arguments used in each call to CarServiceMock.GetCar.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetCar *mCarServiceMockGetCar) Calls() []*CarServiceMockGetCarParams {
	mmGetCar.mutex.RLock()

	argCopy := make([]*CarServiceMockGetCarParams, len(mmGetCar.callArgs))
	copy(argCopy, mmGetCar.callArgs)

	mmGetCar.mutex.RUnlock()

	return argCopy
}

// MinimockGetCarDone returns true if the count of the GetCar invocations corresponds
// the number of defined expectations
func (m *CarServiceMock) MinimockGetCarDone() bool {
	if m.GetCarMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetCarMock.invocationsDone()
}

// MinimockGetCarInspect logs each unmet expectation
func (m *CarServiceMock) MinimockGetCarInspect() {
	for _, e := range m.GetCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CarServiceMock.GetCar at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCarCounter := mm_atomic.LoadUint64(&m.afterGetCarCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetCarMock.defaultExpectation != nil && afterGetCarCounter < 1 {
		if m.GetCarMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CarServiceMock.GetCar at\n%s", m.GetCarMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CarServiceMock.GetCar at\n%s with params: %#v", m.GetCarMock.defaultExpectation.expectationOrigins.origin, *m.GetCarMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCar != nil && afterGetCarCounter < 1 {
		m.t.Errorf("Expected call to CarServiceMock.GetCar at\n%s", m.funcGetCarOrigin)
	}

	if !m.GetCarMock.invocationsDone() && afterGetCarCounter > 0 {
		m.t.Errorf("Expected %d calls to CarServiceMock.GetCar at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetCarMock.expectedInvocations), m.GetCarMock.expectedInvocationsOrigin, afterGetCarCounter)
	}
}

type mCarServiceMockUpdateCar struct {
	optional           bool
	mock               *CarServiceMock
	defaultExpectation *CarServiceMockUpdateCarExpectation
	expectations       []*CarServiceMockUpdateCarExpectation

	callArgs []*CarServiceMockUpdateCarParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CarServiceMockUpdateCarExpectation specifies expectation struct of the CarService.UpdateCar
type CarServiceMockUpdateCarExpectation struct {
	mock               *CarServiceMock
	params             *CarServiceMockUpdateCarParams
	paramPtrs          *CarServiceMockUpdateCarParamPtrs
	expectationOrigins CarServiceMockUpdateCarExpectationOrigins
	results            *CarServiceMockUpdateCarResults
	returnOrigin       string
	Counter            uint64
}

// CarServiceMockUpdateCarParams contains parameters of the CarService.UpdateCar
type CarServiceMockUpdateCarParams struct {
	ctx context.Context
	req *pb.UpdateRequest
}

// CarServiceMockUpdateCarParamPtrs contains pointers to parameters of the CarService.UpdateCar
type CarServiceMockUpdateCarParamPtrs struct {
	ctx *context.Context
	req **pb.UpdateRequest
}

// CarServiceMockUpdateCarResults contains results of the CarService.UpdateCar
type CarServiceMockUpdateCarResults struct {
	err error
}

// CarServiceMockUpdateCarOrigins contains origins of expectations of the CarService.UpdateCar
type CarServiceMockUpdateCarExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateCar *mCarServiceMockUpdateCar) Optional() *mCarServiceMockUpdateCar {
	mmUpdateCar.optional = true
	return mmUpdateCar
}

// Expect sets up expected params for CarService.UpdateCar
func (mmUpdateCar *mCarServiceMockUpdateCar) Expect(ctx context.Context, req *pb.UpdateRequest) *mCarServiceMockUpdateCar {
	if mmUpdateCar.mock.funcUpdateCar != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Set")
	}

	if mmUpdateCar.defaultExpectation == nil {
		mmUpdateCar.defaultExpectation = &CarServiceMockUpdateCarExpectation{}
	}

	if mmUpdateCar.defaultExpectation.paramPtrs != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by ExpectParams functions")
	}

	mmUpdateCar.defaultExpectation.params = &CarServiceMockUpdateCarParams{ctx, req}
	mmUpdateCar.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateCar.expectations {
		if minimock.Equal(e.params, mmUpdateCar.defaultExpectation.params) {
			mmUpdateCar.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateCar.defaultExpectation.params)
		}
	}

	return mmUpdateCar
}

// ExpectCtxParam1 sets up expected param ctx for CarService.UpdateCar
func (mmUpdateCar *mCarServiceMockUpdateCar) ExpectCtxParam1(ctx context.Context) *mCarServiceMockUpdateCar {
	if mmUpdateCar.mock.funcUpdateCar != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Set")
	}

	if mmUpdateCar.defaultExpectation == nil {
		mmUpdateCar.defaultExpectation = &CarServiceMockUpdateCarExpectation{}
	}

	if mmUpdateCar.defaultExpectation.params != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Expect")
	}

	if mmUpdateCar.defaultExpectation.paramPtrs == nil {
		mmUpdateCar.defaultExpectation.paramPtrs = &CarServiceMockUpdateCarParamPtrs{}
	}
	mmUpdateCar.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateCar.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateCar
}

// ExpectReqParam2 sets up expected param req for CarService.UpdateCar
func (mmUpdateCar *mCarServiceMockUpdateCar) ExpectReqParam2(req *pb.UpdateRequest) *mCarServiceMockUpdateCar {
	if mmUpdateCar.mock.funcUpdateCar != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Set")
	}

	if mmUpdateCar.defaultExpectation == nil {
		mmUpdateCar.defaultExpectation = &CarServiceMockUpdateCarExpectation{}
	}

	if mmUpdateCar.defaultExpectation.params != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Expect")
	}

	if mmUpdateCar.defaultExpectation.paramPtrs == nil {
		mmUpdateCar.defaultExpectation.paramPtrs = &CarServiceMockUpdateCarParamPtrs{}
	}
	mmUpdateCar.defaultExpectation.paramPtrs.req = &req
	mmUpdateCar.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmUpdateCar
}

// Inspect accepts an inspector function that has same arguments as the CarService.UpdateCar
func (mmUpdateCar *mCarServiceMockUpdateCar) Inspect(f func(ctx context.Context, req *pb.UpdateRequest)) *mCarServiceMockUpdateCar {
	if mmUpdateCar.mock.inspectFuncUpdateCar != nil {
		mmUpdateCar.mock.t.Fatalf("Inspect function is already set for CarServiceMock.UpdateCar")
	}

	mmUpdateCar.mock.inspectFuncUpdateCar = f

	return mmUpdateCar
}

// Return sets up results that will be returned by CarService.UpdateCar
func (mmUpdateCar *mCarServiceMockUpdateCar) Return(err error) *CarServiceMock {
	if mmUpdateCar.mock.funcUpdateCar != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Set")
	}

	if mmUpdateCar.defaultExpectation == nil {
		mmUpdateCar.defaultExpectation = &CarServiceMockUpdateCarExpectation{mock: mmUpdateCar.mock}
	}
	mmUpdateCar.defaultExpectation.results = &CarServiceMockUpdateCarResults{err}
	mmUpdateCar.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateCar.mock
}

// Set uses given function f to mock the CarService.UpdateCar method
func (mmUpdateCar *mCarServiceMockUpdateCar) Set(f func(ctx context.Context, req *pb.UpdateRequest) (err error)) *CarServiceMock {
	if mmUpdateCar.defaultExpectation != nil {
		mmUpdateCar.mock.t.Fatalf("Default expectation is already set for the CarService.UpdateCar method")
	}

	if len(mmUpdateCar.expectations) > 0 {
		mmUpdateCar.mock.t.Fatalf("Some expectations are already set for the CarService.UpdateCar method")
	}

	mmUpdateCar.mock.funcUpdateCar = f
	mmUpdateCar.mock.funcUpdateCarOrigin = minimock.CallerInfo(1)
	return mmUpdateCar.mock
}

// When sets expectation for the CarService.UpdateCar which will trigger the result defined by the following
// Then helper
func (mmUpdateCar *mCarServiceMockUpdateCar) When(ctx context.Context, req *pb.UpdateRequest) *CarServiceMockUpdateCarExpectation {
	if mmUpdateCar.mock.funcUpdateCar != nil {
		mmUpdateCar.mock.t.Fatalf("CarServiceMock.UpdateCar mock is already set by Set")
	}

	expectation := &CarServiceMockUpdateCarExpectation{
		mock:               mmUpdateCar.mock,
		params:             &CarServiceMockUpdateCarParams{ctx, req},
		expectationOrigins: CarServiceMockUpdateCarExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateCar.expectations = append(mmUpdateCar.expectations, expectation)
	return expectation
}

// Then sets up CarService.UpdateCar return parameters for the expectation previously defined by the When method
func (e *CarServiceMockUpdateCarExpectation) Then(err error) *CarServiceMock {
	e.results = &CarServiceMockUpdateCarResults{err}
	return e.mock
}

// Times sets number of times CarService.UpdateCar should be invoked
func (mmUpdateCar *mCarServiceMockUpdateCar) Times(n uint64) *mCarServiceMockUpdateCar {
	if n == 0 {
		mmUpdateCar.mock.t.Fatalf("Times of CarServiceMock.UpdateCar mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateCar.expectedInvocations, n)
	mmUpdateCar.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateCar
}

func (mmUpdateCar *mCarServiceMockUpdateCar) invocationsDone() bool {
	if len(mmUpdateCar.expectations) == 0 && mmUpdateCar.defaultExpectation == nil && mmUpdateCar.mock.funcUpdateCar == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateCar.mock.afterUpdateCarCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateCar.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateCar implements mm_service.CarService
func (mmUpdateCar *CarServiceMock) UpdateCar(ctx context.Context, req *pb.UpdateRequest) (err error) {
	mm_atomic.AddUint64(&mmUpdateCar.beforeUpdateCarCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateCar.afterUpdateCarCounter, 1)

	mmUpdateCar.t.Helper()

	if mmUpdateCar.inspectFuncUpdateCar != nil {
		mmUpdateCar.inspectFuncUpdateCar(ctx, req)
	}

	mm_params := CarServiceMockUpdateCarParams{ctx, req}

	// Record call args
	mmUpdateCar.UpdateCarMock.mutex.Lock()
	mmUpdateCar.UpdateCarMock.callArgs = append(mmUpdateCar.UpdateCarMock.callArgs, &mm_params)
	mmUpdateCar.UpdateCarMock.mutex.Unlock()

	for _, e := range mmUpdateCar.UpdateCarMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateCar.UpdateCarMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateCar.UpdateCarMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateCar.UpdateCarMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateCar.UpdateCarMock.defaultExpectation.paramPtrs

		mm_got := CarServiceMockUpdateCarParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateCar.t.Errorf("CarServiceMock.UpdateCar got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateCar.UpdateCarMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmUpdateCar.t.Errorf("CarServiceMock.UpdateCar got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateCar.UpdateCarMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateCar.t.Errorf("CarServiceMock.UpdateCar got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateCar.UpdateCarMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateCar.UpdateCarMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateCar.t.Fatal("No results are set for the CarServiceMock.UpdateCar")
		}
		return (*mm_results).err
	}
	if mmUpdateCar.funcUpdateCar != nil {
		return mmUpdateCar.funcUpdateCar(ctx, req)
	}
	mmUpdateCar.t.Fatalf("Unexpected call to CarServiceMock.UpdateCar. %v %v", ctx, req)
	return
}

// UpdateCarAfterCounter returns a count of finished CarServiceMock.UpdateCar invocations
func (mmUpdateCar *CarServiceMock) UpdateCarAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateCar.afterUpdateCarCounter)
}

// UpdateCarBeforeCounter returns a count of CarServiceMock.UpdateCar invocations
func (mmUpdateCar *CarServiceMock) UpdateCarBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateCar.beforeUpdateCarCounter)
}

// Calls returns a list of arguments used in each call to CarServiceMock.UpdateCar.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateCar *mCarServiceMockUpdateCar) Calls() []*CarServiceMockUpdateCarParams {
	mmUpdateCar.mutex.RLock()

	argCopy := make([]*CarServiceMockUpdateCarParams, len(mmUpdateCar.callArgs))
	copy(argCopy, mmUpdateCar.callArgs)

	mmUpdateCar.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateCarDone returns true if the count of the UpdateCar invocations corresponds
// the number of defined expectations
func (m *CarServiceMock) MinimockUpdateCarDone() bool {
	if m.UpdateCarMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateCarMock.invocationsDone()
}

// MinimockUpdateCarInspect logs each unmet expectation
func (m *CarServiceMock) MinimockUpdateCarInspect() {
	for _, e := range m.UpdateCarMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CarServiceMock.UpdateCar at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCarCounter := mm_atomic.LoadUint64(&m.afterUpdateCarCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateCarMock.defaultExpectation != nil && afterUpdateCarCounter < 1 {
		if m.UpdateCarMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CarServiceMock.UpdateCar at\n%s", m.UpdateCarMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CarServiceMock.UpdateCar at\n%s with params: %#v", m.UpdateCarMock.defaultExpectation.expectationOrigins.origin, *m.UpdateCarMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateCar != nil && afterUpdateCarCounter < 1 {
		m.t.Errorf("Expected call to CarServiceMock.UpdateCar at\n%s", m.funcUpdateCarOrigin)
	}

	if !m.UpdateCarMock.invocationsDone() && afterUpdateCarCounter > 0 {
		m.t.Errorf("Expected %d calls to CarServiceMock.UpdateCar at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateCarMock.expectedInvocations), m.UpdateCarMock.expectedInvocationsOrigin, afterUpdateCarCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CarServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateCarInspect()

			m.MinimockDeleteCarInspect()

			m.MinimockGetCarInspect()

			m.MinimockUpdateCarInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CarServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CarServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateCarDone() &&
		m.MinimockDeleteCarDone() &&
		m.MinimockGetCarDone() &&
		m.MinimockUpdateCarDone()
}
